// Copyright ©2026 Scott Blomfield
/*
 *  This program is free software: you can redistribute it and/or modify it under the terms of the
 *  GNU General Public License as published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program. If not,
 *  see <https://www.gnu.org/licenses/>. 
 */

namespace JumpStart.Api.DTOs;

/// <summary>
/// Marker interface for DTOs used in update (PUT/PATCH) operations.
/// Update DTOs must include an Id to identify the entity being updated,
/// but should not include audit fields as these are system-managed.
/// </summary>
/// <typeparam name="TKey">The type of the entity identifier. Must be a value type (struct) such as int, long, or Guid.</typeparam>
/// <remarks>
/// <para>
/// This interface extends <see cref="IDto"/> to identify DTOs specifically designed for
/// entity update operations. Unlike <see cref="ICreateDto"/>, update DTOs must include
/// the Id property to identify which entity to update.
/// </para>
/// <para>
/// <strong>Fields to INCLUDE in Update DTOs:</strong>
/// - Id (required to identify the entity being updated)
/// - All business properties that can be modified
/// - Optional fields with appropriate nullable types
/// - Navigation properties as IDs or nested update DTOs
/// </para>
/// <para>
/// <strong>Fields to EXCLUDE from Update DTOs:</strong>
/// - CreatedById (set during creation, cannot be changed)
/// - CreatedOn (set during creation, cannot be changed)
/// - ModifiedById (set from current user context by the system)
/// - ModifiedOn (set to current UTC timestamp by the system)
/// - DeletedById (managed through delete operations, not updates)
/// - DeletedOn (managed through delete operations, not updates)
/// </para>
/// <para>
/// <strong>Update vs. Create DTOs:</strong>
/// The key difference between update and create DTOs:
/// - Update DTOs MUST have Id property (required by this interface)
/// - Create DTOs must NOT have Id (generated by the system)
/// - Both exclude audit fields (CreatedOn, ModifiedOn, etc.)
/// - Both include business properties that clients can provide
/// </para>
/// <para>
/// The generic TKey parameter allows flexibility in identifier types (int, long, Guid, etc.)
/// and ensures type safety when matching update DTOs with their corresponding entities.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Example 1: Simple update DTO for a Product
/// public class UpdateProductDto : IUpdateDto&lt;int&gt;
/// {
///     public int Id { get; set; } // Required by IUpdateDto
///     
///     [Required]
///     [StringLength(200)]
///     public string Name { get; set; } = string.Empty;
///     
///     [Required]
///     [Range(0.01, double.MaxValue)]
///     public decimal Price { get; set; }
///     
///     [StringLength(1000)]
///     public string? Description { get; set; }
///     
///     public int CategoryId { get; set; }
/// }
/// 
/// // Example 2: Update DTO with Guid identifier
/// public class UpdateCustomerDto : IUpdateDto&lt;Guid&gt;
/// {
///     public Guid Id { get; set; } // Required by IUpdateDto
///     
///     [Required]
///     [StringLength(100)]
///     public string Name { get; set; } = string.Empty;
///     
///     [EmailAddress]
///     public string Email { get; set; } = string.Empty;
///     
///     public bool IsActive { get; set; }
/// }
/// 
/// // Example 3: Update DTO with nested objects
/// public class UpdateOrderDto : IUpdateDto&lt;long&gt;
/// {
///     public long Id { get; set; } // Required by IUpdateDto
///     
///     public DateTime OrderDate { get; set; }
///     
///     public List&lt;UpdateOrderItemDto&gt; Items { get; set; } = new();
///     
///     public string? Notes { get; set; }
/// }
/// 
/// public class UpdateOrderItemDto : IUpdateDto&lt;long&gt;
/// {
///     public long Id { get; set; }
///     public int ProductId { get; set; }
///     
///     [Range(1, int.MaxValue)]
///     public int Quantity { get; set; }
/// }
/// 
/// // Example 4: Usage in API controller
/// [HttpPut("{id}")]
/// public async Task&lt;ActionResult&lt;ProductDto&gt;&gt; Update(int id, [FromBody] UpdateProductDto updateDto)
/// {
///     // Verify URL id matches DTO id
///     if (id != updateDto.Id)
///         return BadRequest("ID mismatch");
///     
///     // Retrieve existing entity
///     var entity = await _repository.GetByIdAsync(id);
///     if (entity == null)
///         return NotFound();
///     
///     // Map update DTO to entity (preserving audit fields)
///     _mapper.Map(updateDto, entity);
///     
///     // Repository updates ModifiedOn and ModifiedById automatically
///     var updated = await _repository.UpdateAsync(entity);
///     var dto = _mapper.Map&lt;ProductDto&gt;(updated);
///     
///     return Ok(dto);
/// }
/// </code>
/// </example>
/// <seealso cref="IDto"/>
/// <seealso cref="ICreateDto"/>
public interface IUpdateDto<TKey> : IDto where TKey : struct
{
    /// <summary>
    /// Gets or sets the unique identifier of the entity being updated.
    /// This property is required to identify which entity to modify.
    /// </summary>
    /// <value>
    /// A value of type <typeparamref name="TKey"/> that uniquely identifies the entity to update.
    /// This must match an existing entity's Id in the data store.
    /// </value>
    /// <remarks>
    /// <para>
    /// The Id property serves multiple purposes in update operations:
    /// - Identifies which entity to update in the database
    /// - Provides URL-to-body consistency validation (URL id should match DTO id)
    /// - Enables optimistic concurrency when combined with versioning
    /// - Allows AutoMapper to match update DTO with existing entity
    /// </para>
    /// <para>
    /// Best practices for Id in update DTOs:
    /// - Always validate that URL id parameter matches DTO Id
    /// - Use the Id to retrieve the existing entity before updating
    /// - Never allow Id to be changed during an update operation
    /// - Consider using Id in optimistic concurrency checks
    /// </para>
    /// </remarks>
    TKey Id { get; set; }
}
