// Copyright ©2026 Scott Blomfield
/*
 *  This program is free software: you can redistribute it and/or modify it under the terms of the
 *  GNU General Public License as published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program. If not,
 *  see <https://www.gnu.org/licenses/>. 
 */

namespace JumpStart.Api.DTOs;

/// <summary>
/// Marker interface for DTOs used in update (PUT/PATCH) operations.
/// Update DTOs must include an Id to identify the entity being updated, but should not include audit fields as these are system-managed.
/// </summary>
/// <remarks>
/// <para>
/// This interface extends <see cref="JumpStart.Api.DTOs.IDto"/> to identify DTOs specifically designed for entity update operations. Unlike <see cref="JumpStart.Api.DTOs.ICreateDto"/>, update DTOs must include the Id property to identify which entity to update.
/// </para>
/// <para>
/// <strong>Fields to INCLUDE in Update DTOs:</strong>
/// - Id (required to identify the entity being updated)
/// - All business properties that can be modified
/// - Optional fields with appropriate nullable types
/// - Navigation properties as IDs or nested update DTOs
/// </para>
/// <para>
/// <strong>Fields to EXCLUDE from Update DTOs:</strong>
/// - CreatedById (set during creation, cannot be changed)
/// - CreatedOn (set during creation, cannot be changed)
/// - ModifiedById (set from current user context by the system)
/// - ModifiedOn (set to current UTC timestamp by the system)
/// - DeletedById (managed through delete operations, not updates)
/// - DeletedOn (managed through delete operations, not updates)
/// </para>
/// <para>
/// <strong>Update vs. Create DTOs:</strong>
/// The key difference between update and create DTOs:
/// - Update DTOs MUST have Id property (required by this interface)
/// - Create DTOs must NOT have Id (generated by the system)
/// - Both exclude audit fields (CreatedOn, ModifiedOn, etc.)
/// - Both include business properties that clients can provide
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Example: Simple update DTO for a form
/// public class UpdateFormDto : JumpStart.Api.DTOs.IUpdateDto
/// {
///     [System.ComponentModel.DataAnnotations.Required]
///     public System.Guid Id { get; set; }
///     [System.ComponentModel.DataAnnotations.Required]
///     [System.ComponentModel.DataAnnotations.StringLength(200)]
///     public string Name { get; set; } = string.Empty;
///     [System.ComponentModel.DataAnnotations.StringLength(1000)]
///     public string? Description { get; set; }
/// }
/// </code>
/// </example>
/// <seealso cref="JumpStart.Api.DTOs.IDto"/>
/// <seealso cref="JumpStart.Api.DTOs.ICreateDto"/>
public interface IUpdateDto : IDto
{
    /// <summary>
    /// Gets or sets the unique identifier of the entity being updated.
    /// This property is required to identify which entity to modify.
    /// </summary>
    /// <value>
    /// A value of type <typeref name="Guid"/> that uniquely identifies the entity to update.
    /// This must match an existing entity's Id in the data store.
    /// </value>
    /// <remarks>
    /// <para>
    /// The Id property serves multiple purposes in update operations:
    /// - Identifies which entity to update in the database
    /// - Provides URL-to-body consistency validation (URL id should match DTO id)
    /// - Enables optimistic concurrency when combined with versioning
    /// - Allows AutoMapper to match update DTO with existing entity
    /// </para>
    /// <para>
    /// Best practices for Id in update DTOs:
    /// - Always validate that URL id parameter matches DTO Id
    /// - Use the Id to retrieve the existing entity before updating
    /// - Never allow Id to be changed during an update operation
    /// - Consider using Id in optimistic concurrency checks
    /// </para>
    /// </remarks>
    Guid Id { get; set; }
}
