// Copyright ©2026 Scott Blomfield
/*
 *  This program is free software: you can redistribute it and/or modify it under the terms of the
 *  GNU General Public License as published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program. If not,
 *  see <https://www.gnu.org/licenses/>. 
 */

using System;

namespace JumpStart.Data;

/// <summary>
/// Defines the base contract for all entities with a unique <see cref="System.Guid"/> identifier.
/// This is the fundamental interface for entity identification in the JumpStart framework.
/// </summary>
/// <remarks>
/// <para>
/// This interface establishes the core contract for entity identification across the JumpStart framework.
/// Every entity that needs to be uniquely identifiable must implement this interface, either directly or
/// through one of the framework's base classes that implement it.
/// </para>
/// <para>
/// <strong>Purpose and Design:</strong>
/// The interface defines a single property, <c>Id</c>, which serves as the unique identifier for the entity.
/// </para>
/// <para>
/// <strong>When to Use:</strong>
/// - Implement this interface directly when creating custom entity base classes
/// - Use as a generic constraint in repositories, services, and other generic code
/// - Reference this interface for polymorphic collections of different entity types
/// - Leverage in LINQ queries that work across multiple entity types
/// </para>
/// <para>
/// <strong>Common Implementations:</strong>
/// Rather than implementing this interface directly, use one of these base classes:
/// - <see cref="JumpStart.Data.Entity"/> - Basic entity with Guid key
/// - <see cref="Data.Auditing.AuditableEntity"/> - Entity with full audit tracking
/// - <see cref="JumpStart.Data.NamedEntity"/> - Entity with Name property
/// </para>
/// <para>
/// <strong>Generic Repository Pattern:</strong>
/// This interface enables powerful generic programming patterns, particularly for repositories
/// and data access layers. A single generic repository implementation can work with any entity
/// type that implements IEntity, reducing code duplication and improving maintainability.
/// </para>
/// </remarks>
/// <seealso cref="JumpStart.Data.Entity"/>
/// <seealso cref="JumpStart.Data.NamedEntity"/>
/// <seealso cref="Data.Auditing.AuditableEntity"/>
/// <seealso cref="Data.Auditing.AuditableNamedEntity"/>
/// <example>
/// <code>
/// // Example 1: Simple Product Entity
/// public class Product : JumpStart.Data.Entity
/// {
///     [System.ComponentModel.DataAnnotations.Required]
///     [System.ComponentModel.DataAnnotations.StringLength(200)]
///     public string Name { get; set; } = string.Empty;
///     public decimal Price { get; set; }
/// }
///
/// // Example 2: Auditable Entity
/// public class Invoice : JumpStart.Data.Auditing.AuditableEntity
/// {
///     public decimal Amount { get; set; }
///     public string InvoiceNumber { get; set; } = string.Empty;
/// }
///
/// // Example 3: Tenant-Scoped Entity
/// public class Customer : JumpStart.Data.Entity, JumpStart.Data.MultiTenant.ITenantScoped
/// {
///     public System.Guid TenantId { get; set; }
///     public JumpStart.Data.Tenant Tenant { get; set; } = null!;
///     public string Name { get; set; } = string.Empty;
/// }
/// </code>
/// </example>
public interface IEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for the entity.
    /// </summary>
    /// <value>
    /// The unique identifier of the record.
    /// </value>
    /// <remarks>
    /// <para>
    /// This property serves as the primary key for the entity. The identifier must be unique within
    /// the entity's scope (typically the database table). 
    /// </para>
    /// <para>
    /// <strong>Id Generation Strategies:</strong>
    /// - Guid: Can be generated by application (Guid.NewGuid()) or database (NEWSEQUENTIALID())
    /// </para>
    /// <para>
    /// <strong>Default Value Semantics:</strong>
    /// A default value (Guid.Empty) typically indicates a new entity
    /// that has not yet been persisted to the database. This convention is used by repositories
    /// to determine whether to perform an insert or update operation.
    /// </para>
    /// <para>
    /// <strong>Usage Guidelines:</strong>
    /// - Set before saving for Guid keys if using application-side generation
    /// - Use to determine entity equality (two entities with same Id are considered the same)
    /// - Use in repository methods for entity lookup (GetById, Update, Delete)
    /// - Check against default to determine if entity is new or existing
    /// </para>
    /// </remarks>
    Guid Id { get; set; }
}
